
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/stylized_planet.glb --transform --types --keepnames --root /models/
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
-->




    <script lang="ts">
				
	
import type * as THREE from 'three'
	import { Group } from 'three'
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf, useGltfAnimations } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> &  {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()

				

				ref = new Group()

        type ActionName = "Animation";
type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh,Object_6: THREE.Mesh
      
    }
    materials: {
      Clouds: THREE.MeshBasicMaterial,Planet: THREE.MeshBasicMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/models/stylized_planet-transformed.glb')

    export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
    </script>

		<T is={ref}  dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group name="Sketchfab_Scene" >
<T.Group name="Sketchfab_model" rotation={[-1.54, -0.06, 0,]} >
<T.Group name="root" >
<T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0,]} >
<T.Group name="Clouds_1" >
<T.Mesh name="Object_4" geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Clouds} />

</T.Group>
<T.Group name="Planet_2" >
<T.Mesh name="Object_6" geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Planet} />

</T.Group>

</T.Group>

</T.Group>

</T.Group>

</T.Group>

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T>
	